name: Copy Specific Files on New Upload

on:
  push:
    branches:
      - main # Or your main branch name
    paths:
      - 'generated/**'

jobs:
  copy_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})
          echo "::set-output name=files::$CHANGED_FILES"

      - name: Copy specific files if they exist in generated/
        run: |
          FILES_TO_COPY="computer_operation_procedure_manual.md data_catalogue.md program_spec.md program_manual.md"
          for FILE in $FILES_TO_COPY; do
            if echo "${{ steps.changed-files.outputs.files }}" | grep -q "generated/$FILE"; then
              echo "Copying generated/$FILE to source/$FILE"
              mkdir -p source # Create source directory if it doesn's exist
              cp "generated/$FILE" "source/$FILE"
            fi
          done

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Copy specific files from generated/ to source/'
          push_options: '--force' #Optional but ensures that a failed action doesn't break the file transfer and updates GitHub history to reflect
