name: Copy Specific Generated Files to Source

on:
  push:
    branches:
      - main # or your main branch name
    paths:
      - 'generated/**' # Trigger only when files in 'generated' folder are changed

jobs:
  copy_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Identify and Copy Specific Files
        run: |
          TARGET_FILES="computer_operation_procedure_manual.md data_catalogue.md program_spec.md program_manual.md"
          GENERATED_FOLDER="generated"
          SOURCE_FOLDER="source"

          # Ensure source folder exists
          mkdir -p "$SOURCE_FOLDER"

          # Get the list of changed files in the 'generated' folder during the push
          CHANGED_FILES=$(git diff --name-only --diff-filter=AMR HEAD~1 HEAD -- "$GENERATED_FOLDER")

          if [[ -n "$CHANGED_FILES" ]]; then # Check if there are any changed files in 'generated'
            while IFS= read -r file; do
              filename=$(basename "$file") # Extract filename from path

              # Check if the filename is in the target list
              if [[ " $TARGET_FILES " =~ " $filename " ]]; then
                echo "Detected target file: $filename in $GENERATED_FOLDER"

                # Construct source and destination paths
                source_path="$GENERATED_FOLDER/$filename"
                destination_path="$SOURCE_FOLDER/$filename"

                # Copy the file
                echo "Copying $source_path to $destination_path"
                cp "$source_path" "$destination_path"
                echo "File copied successfully."
              fi
            done < <(echo "$CHANGED_FILES")
          else
            echo "No files changed in '$GENERATED_FOLDER' or no relevant files found."
          fi
