name: Copy Generated Files to Source

on:
  push:
    branches:
      - main
    paths:
      - 'generated/computer_operation_procedure_manual.md'
      - 'generated/data_catalogue.md'
      - 'generated/program_spec.md'
      - 'generated/program_manual.md'

jobs:
  copy_files:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
      - name: Copy specific files from generated to source
        run: |
          # Create source directory if it doesn't exist
          mkdir -p source
          
          # Check if each file exists in generated folder and copy to source
          for file in computer_operation_procedure_manual.md data_catalogue.md program_spec.md program_manual.md; do
            if [ -f "generated/$file" ]; then
              echo "Copying $file to source folder"
              cp "generated/$file" "source/$file"
            fi
          done
          
      - name: Commit and push changes if any files were copied
        run: |
          # Check if there are any changes
          if git diff --quiet source/; then
            echo "No changes to commit"
            exit 0
          fi
          
          # Stage, commit and push changes
          git add source/
          git commit -m "Automatically copy files from generated to source"
          git push
